"""Update many2many relationship

Revision ID: 98969f2b8ef4
Revises: 89c31b9be6d6
Create Date: 2020-09-17 11:15:43.008440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98969f2b8ef4'
down_revision = '89c31b9be6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
